- name: Enable phpMyAdmin via Apache, if phpmyadmin_enabled
  command: a2ensite phpmyadmin.conf
  when: phpmyadmin_enabled
  #when: apache_installed is defined and phpmyadmin_enabled

- name: Disable phpMyAdmin via Apache, if not phpmyadmin_enabled
  command: a2dissite phpmyadmin.conf
  when: not phpmyadmin_enabled
  #when: apache_installed is defined and not phpmyadmin_enabled
